### ISSUE TITLE
scfbuild fails on TTX/FontTools version number

### ISSUE THREAD

**Issue by RoelN** [13rac1/scfbuild#12]
I'm using TTX/FontTools compiled from source instead if through pip, and I get an error on the version number:

```
Traceback (most recent call last):
  File "/Users/roel/code/scfbuild/bin/scfbuild", line 14, in <module>
    from scfbuild.main import main
  File "/Users/roel/code/scfbuild/scfbuild/main.py", line 18, in <module>
    from .builder import Builder
  File "/Users/roel/code/scfbuild/scfbuild/builder.py", line 31, in <module>
    if StrictVersion('2.5') > StrictVersion(fontTools.version):
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/version.py", line 40, in __init__
    self.parse(vstring)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/version.py", line 107, in parse
    raise ValueError, "invalid version number '%s'" % vstring
ValueError: invalid version number '3.5.0.dev0'
```

**Comment by DeeDeeG** [comment]
Also happens to me, although my version of fonttools show up as "3.5.1.dev0". The error message is the same other than the different version number.

```
Traceback (most recent call last):
  File "SCFBuild/bin/scfbuild", line 14, in <module>
    from scfbuild.main import main
  File "/home/mint/noto-color-emoji-font/SCFBuild/scfbuild/main.py", line 18, in <module>
    from .builder import Builder
  File "/home/mint/noto-color-emoji-font/SCFBuild/scfbuild/builder.py", line 31, in <module>
    if StrictVersion('2.5') > StrictVersion(fontTools.version):
  File "/usr/lib/python2.7/distutils/version.py", line 40, in __init__
    self.parse(vstring)
  File "/usr/lib/python2.7/distutils/version.py", line 107, in parse
    raise ValueError, "invalid version number '%s'" % vstring
ValueError: invalid version number '3.5.1.dev0'
```

As RoeIN mentioned, folks can work around this at the moment by using the pip version. (worked for me).
```
sudo pip uninstall fonttools
sudo pip install fonttools
```

**Comment by RoelN** [comment]
As a workaround, you can also comment out the version check in `scfbuild/builder.py`:

```
# Support for SVG tables was added to fontTools in version 2.5
if StrictVersion('2.5') > StrictVersion(fontTools.version):
    logger.exception("The FontTools module version must be 2.5 or higher.")
    sys.exit(1)
```

**Comment by 13rac1** [comment]
Should I just drop this version check?

It's far enough in the past now.

**Comment by RoelN** [comment]
The problem seems to be that TTX/FontTools doesn't use a version string that is considered valid by StrictVersion, so you'd either have to build a check that can handle the `3.5.0.dev0`-like notation, or ask TTX/FontTools to change their versioning. Or indeed just drop the check ;)

**Comment by DeeDeeG** [comment]
You could perhaps chop the fontTools.version string to 5 characters, starting from the first character, eg "3.5.x". Or chop it down to 3 characters, eg "3.x" and feed that to StrictVersion. . .

(I don't really know python, but a guide on the internet says something like "varnamehere[0:3]" will do it.) 

That way is unlikely to blow up StrictVersion. You could also remove StrictVersion from the pipeline entirely.

> Or indeed just drop the check ;) 

👍

Edit: Or use LooseVersion instead of StrictVersion? LooseVersion wouldn't blow up with version number "3.5.0.dev0" and I think it still understands the numbers from left to right.

Edit2: I can confirm that "LooseVersion" works.

Also works: comparing the bare version number strings, not using any version checking functions (until fonttools gets to version 10 or greater, after which point the bare-string comparison stops working.)

Apparently there are competing tools out there do version number comparisons. More details: http://stackoverflow.com/questions/11887762/compare-version-strings

Fonttools seems to be conforming to some spec called [PEP 440](https://www.python.org/dev/peps/pep-0440/) which is supported by the "packaging.version.parse" library. Dunno if all this info is needed, but it was out there.
